# vi:syntax=ruby
###################### More Options ######################
# If you want to have even more control, check out the documentation
# https://github.com/KrauseFx/deliver/blob/master/Deliverfile.md

default_language "en-US"

hide_transporter_output

copyright "#{Time.now.year} Thought Croft Pty Ltd"
